### PR TITLE
made buttons UI update on click

### PR DESCRIPTION
**Pull request by naikibro**
- updated the handleClick method
- added vertical props handling between `WarfieldPage` and `MapComponent`

References #27

### CODE REVIEW

**Comment by naikibro** [comment]
# Screencast 
 please notice:
- the color updates on click depending on the tile content
- the player is updated after a valid click
- an empty tile becomes blue
- a destroyed ship becomes red
- a tile cannot be clicked more than once

[Screencast from 05-28-2024 08:14:36 PM.webm](https://github.com/naikibro/BatailleNavale/assets/64978347/6ac56ee1-898f-4684-9dc2-aca70cc53ef9)

**Comment by naikibro** [comment]
on player turn change, displayed map should be updated
- ennemy player map should be hidden

**Comment by naikibro** [comment]
thanks @tteuru09 for the help with #35 💪

**Review by tteuru09 — APPROVED** [review]
LVGTM ! 😉

**Pull request merged**
